version: '2'
services:
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33060:33060"
      - "3306:3306"
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: planes
      MYSQL_USER: planes
      MYSQL_PASSWORD: password