version: '2'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-bismuth
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
      image: selenium/node-chrome:3.141.59-bismuth
      container_name: chrome
      depends_on:
        - selenium-hub
        - planes-site
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
  planes-site:
      build: planes-4-sale-site/.
      container_name: planes-site
      depends_on:
        - db
      ports:
        - "8080:8080"
        - "8081:8081"
  planes-monitoring:
      build: acceptance-tests-as-monitors/.
      container_name: planes-monitoring
      depends_on:
        - selenium-hub
        - planes-site
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - "9090:9090"
        - "9091:9091"
  db:
    image: mysql:8.0.16
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33060:33060"
      - "3306:3306"
    volumes:
      - ./db/db-init/:/docker-entrypoint-initdb.d
      - ./db/storage/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: planes
      MYSQL_USER: planes
      MYSQL_PASSWORD: password