
# Dropwizard server configuration
server:

  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
      - type: http
        port: 8081

  requestLog:
    appenders:
      - type: console
        # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
        timeZone: UTC

logging:
  level: INFO
  appenders:
    - type: console

database:
  # the name of your JDBC driver
  driverClass: com.mysql.cj.jdbc.Driver

  # the username
  user: planes

  # the password
  password: password

  # the JDBC URL
  url: jdbc:mysql://db:3306/planes

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8