
# Dropwizard server configuration
server:

  applicationConnectors:
    - type: http
      port: 9090

  adminConnectors:
      - type: http
        port: 9091

  requestLog:
    appenders:
      - type: console
        # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
        timeZone: UTC

logging:
  level: INFO
  appenders:
    - type: console